[2024-12-23T18:45:53.926499] - URL: https://www.idealista.com/inmueble/106882313/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:53.955501] - URL: https://www.idealista.com/inmueble/106882793/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:53.959500] - URL: https://www.idealista.com/inmueble/106882822/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:53.987496] - URL: https://www.idealista.com/inmueble/106882272/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:53.997498] - URL: https://www.idealista.com/inmueble/106882311/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:54.027500] - URL: https://www.idealista.com/inmueble/106882729/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:54.115500] - URL: https://www.idealista.com/inmueble/106882565/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:54.130508] - URL: https://www.idealista.com/inmueble/106542638/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:45:54.158497] - URL: https://www.idealista.com/inmueble/106882824/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: update_date'
 
[2024-12-23T18:49:04.156434] - URL: https://www.idealista.com/inmueble/106885548/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.164435] - URL: https://www.idealista.com/inmueble/106885725/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.174436] - URL: https://www.idealista.com/inmueble/106881344/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.208479] - URL: https://www.idealista.com/inmueble/106885345/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.219443] - URL: https://www.idealista.com/inmueble/106885335/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.249434] - URL: https://www.idealista.com/inmueble/106887240/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
[2024-12-23T18:49:04.261434] - URL: https://www.idealista.com/inmueble/106886777/ 
 Traceback (most recent call last):
  File "E:\SpainHouses\crawler\realEstateCrawler\spiders\idealista.py", line 196, in parseAnnouncement
    yield AnnouncementItem(
          ^^^^^^^^^^^^^^^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 76, in __init__
    self[k] = v
    ~~~~^^^
  File "C:\Users\skait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scrapy\item.py", line 85, in __setitem__
    raise KeyError(f"{self.__class__.__name__} does not support field: {key}")
KeyError: 'AnnouncementItem does not support field: titl'
 
